spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbatchtest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always


